### ISSUE TITLE
Support Referrals

### ISSUE THREAD

**Issue by stuartmscott** [AletheiaWareLLC/conveyearthgo#15]
Referrals reward members when they invite others to expand the community. How should this mechanic work in Convey?

Options;
1. Fixed coin reward for each referral that signs up - the downside is it encourages account creation, but not content contribution or discussion engagement.
2. Coin reward based on referral's first coin purchase - encourages account creation and coin purchases, but again not contribution or engagement.
3. Coin reward based on referral's first conversation's yield - encourages member to invite people the believe will do well on Convey and generate a high yield
4. Coin reward based on referral's first digest publication's reward - similar to 3, but slightly more forgiving (a new user's first post might not be as successful as a later post)

Any other ideas?

**Comment by mattknox** [comment]
What do you want to incent?  I'd argue it should be some combination of "bring in users who pay" and "bring in users who play the content game well".  I'd say that for today, the content is way more valuable than the money, so I'd just reduce it to some function of referred users' earnings.

**Comment by stuartmscott** [comment]
I agree the priority for now is to incentivize content and engagement, so basing referrer's reward on the referral's earnings makes sense.

**Comment by stuartmscott** [comment]
Do you have a preference between these two approaches?
1. You enter a friend's email, platform send them an email invitation
2. Platform issues you a code/link, you give that to your friend

**Comment by mattknox** [comment]
I'd go with 2-it's strictly more capable, although it is less amenable to people just spamming all their email contacts.

**Comment by stuartmscott** [comment]
Referrals are now supported! Head over to https://convey.earth/account to find your referral link and invite your friends - you'll get a reward whenever any of your referrals appear in the digest
