### ISSUE TITLE
Enable Deleting

### ISSUE THREAD

**Issue by stuartmscott** [AletheiaWareLLC/conveyearthgo#3]
The author should be able to edit topics and text content.

Non-text attachments are out of this ticket's scope.

**Comment by stuartmscott** [comment]
One concern raised is that an author could change the sentiment of their post, resulting in existing responses expressing support for something which the responder did not intend.

In a discussion with @winksaville the idea was explored of only allowing edits if there were no responses. This would enable authors to quickly correct typos and other errors without allowing the "bait and switch" issue.

Perhaps there would also be a time limit after edits are not allowed.

**Comment by stuartmscott** [comment]
Edit and Delete are both useful options, however they don't both need to be implemented - Edit can be achieved with a Delete and Create. So, in the interest of simplicity and intuitiveness, I'm retargeting this ticket to "Enable Deleting".

As before, the delete option will only be available when a message has no replies or gifts. There may also be a time limit, although this duration has not been decided, and anyway can be added at a later time.

Now the question is whether the operation should be hard (data is wiped from database/server) or soft (data is marked as deleted, but still persisted - more akin to 'hide' than 'delete'). In both cases, accessing a deleted message will fail and the content will not appear on the website or in the digest. Soft delete has the advantage that the data is available for future operations (such as undo, audits, and analytics), with the disadvantage of the performance penalty & storage cost incurred. 

It could be possible to get the best of both worlds with a "garbage collector" that hard deletes any records that were soft deleted more than X years ago.

Another option I've seen is duplicating the tables, so there are active and inactive tables - delete means delete from active and insert to inactive, but this seems overcomplicated.

I'm open to anecdotes, opinions, and suggestions :)

(cc @Kostadin)

**Comment by winksaville** [comment]
This make sense from the context of seeing Convey for conversing and you can't have people changing the meaning of a old message as the old comments might not make sense.

But another way to potentially use Convey is create a living "document" which is created from the conversation. In that sense you'd like the document to be editable in response to comments and the editors/viewers should be able to see all versions of the document and comments leading up to that version. So I see deleting different from editing.

**Comment by stuartmscott** [comment]
Fair point @winksaville. I see Convey more as you described in your first part - a tool for discussion and conversation, rather than a competitor to a wiki/Google Docs for living documents. The value is in the journey of the dialogue, rather than the destination. Where various viewpoints and perspectives are compared and contrasted in respectful and insightful debate. Or where a richer story is told through collaboration and contribution of smaller parts.
